// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261004194302_AddKitchen")]
    partial class AddKitchen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Catalog.Pizza", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsOnMenu")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");
                });

            modelBuilder.Entity("Domain.Kitchen.Baker", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxConcurrentPizzas")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("PreparationTimePerPizza")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Bakers");
                });

            modelBuilder.Entity("Domain.Kitchen.Oven", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("BakingTime")
                        .HasColumnType("time");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ovens");
                });

            modelBuilder.Entity("Domain.Kitchen.Workstation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkBaker")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkOven")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FkBaker")
                        .IsUnique();

                    b.HasIndex("FkOven")
                        .IsUnique();

                    b.ToTable("Workstations");
                });

            modelBuilder.Entity("Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DailyNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("FkWorkstation")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ReadyAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FkWorkstation");

                    b.HasIndex("BusinessDate", "DailyNumber")
                        .IsUnique();

                    b.HasIndex("Status", "BusinessDate", "DailyNumber");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Domain.Orders.OrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkOrder")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PizzaName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("FkOrder");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("Domain.Kitchen.Workstation", b =>
                {
                    b.HasOne("Domain.Kitchen.Baker", "FkBakerNavigation")
                        .WithMany()
                        .HasForeignKey("FkBaker")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Kitchen.Oven", "FkOvenNavigation")
                        .WithMany()
                        .HasForeignKey("FkOven")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FkBakerNavigation");

                    b.Navigation("FkOvenNavigation");
                });

            modelBuilder.Entity("Domain.Orders.Order", b =>
                {
                    b.HasOne("Domain.Kitchen.Workstation", "FkWorkstationNavigation")
                        .WithMany()
                        .HasForeignKey("FkWorkstation")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FkWorkstationNavigation");
                });

            modelBuilder.Entity("Domain.Orders.OrderLine", b =>
                {
                    b.HasOne("Domain.Orders.Order", "FkOrderNavigation")
                        .WithMany("Lines")
                        .HasForeignKey("FkOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FkOrderNavigation");
                });

            modelBuilder.Entity("Domain.Orders.Order", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
